name = "mita"
license = "MIT"
licenselink = "https://github.com/vinlia/mita/blob/master/LICENSE"
description = "a zero-nonsense hugo theme for writers"
homepage = "https://github.com/vinliao/mita"
tags = ["blog", "milligram"]
features = ["blog", "responsive", "zero-nonsense"]
min_version = "0.55.2"

[author]
    name = "vinliao"
    homepage = "https://github.com/vinliao"