name = "mita"
license = "MIT"
licenselink = "https://github.com/vinlia/mita/blob/master/LICENSE"
description = "A hugo theme that feels like a milligram"
homepage = "https://github.com/vinliao/mita"
tags = ["blog", "milligram", "light"]
features = ["blog", "responsive", "zero-nonsense", "milligram"]
min_version = "0.55.2"

[author]
    name = "vinliao"
    homepage = "https://github.com/vinliao"
